### ISSUE TITLE
Integration with Python Index (PyPi)

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#109]
We should finally make our project available in the Python Index (PyPi)

**Comment by aleksandervines** [comment]
It's easy enough to make it available. It's "just" to make sure I have required dependencies installed locally, and run

```
python setup.py sdist
python setup.py bdist_wheel
```

It will then build the extensions and package the files specifically for the platform you are on. You would need to repeat the process for each platform, and 2x more when python 3 support is out.

The issue is that I think we will have large version issues with gdal unless we set one specific version of gdal to support.

I need to figure out which versions are easily available, I will start looking into providing it easily on windows, os x, and ubuntu.

Are there known issues with some versions of gdal for nansat?

**Comment by aleksandervines** [comment]
And then there is numpy.. which is required by gdal, scipy and basemap. When I try to install these from apt, it seems the repositories are not synchronized, so I end up getting the error from numpy:
`RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa`

I suggest we wait with the pypi integration until we have updated master from develop, and a lot of these dependencies have been removed. Should simplify the problem greatly. Anaconda is a fantastic tool and I recommend using it anyway :P

**Comment by aleksandervines** [comment]
Actually.

We can not build a wheel, but have to provide the source code only. And it is super easy. But the user will need to install all dependencies properly, and that is not very user friendly.

I've found a procedure that I've tested on the lastest ubuntu 16.04 which we can present to users. But it's fragile to changes:
```
sudo apt install virtualenv git libgdal1-dev python-dev python-gdal python-numpy python-scipy python-matplotlib python-mpltoolkits.basemap python-requests
virtualenv --no-site-packages nansat_env
source ~/nansat_env/bin/activate
export PYTHONPATH=/usr/lib/python2.7/dist-packages/
pip install pythesint pillow cfunits netcdf4
pip install https://testpypi.python.org/packages/c5/7c/c0a6263eed8725e970c7112aefb5791ac2171d69244be606657fd8bb8f6d/nansat-0.6.17.tar.gz#md5=454efd7b4c8a1853ab1b844f1c201449
pip install nose
nosetests nansat
```

This is how the two common gdal-python bindings available on pypi has done it. They have less requirements though (only gdal+numpy).

https://pypi.python.org/pypi/GDAL/2.2.3
https://pypi.python.org/pypi/pygdal/2.2.1.3
