### ISSUE TITLE
Integration with Anaconda (linux)

### ISSUE THREAD

**Issue by akorosov** [nansencenter/nansat#111]
Anaconda is a very user-friendly distribution of Python with up-to-date Numpy, Scipy, Matplotlib, Basemap. It is relatively easy to add software to this distribution via http://binstar.org. But it doesn't always work as expected (e.g. GDAL doesn't work on Ubuntu). We should make Nansat available through anaconda/binstar. First we do that for linux.

**Comment by akorosov** [comment]
GDAL is already integrated in Anaconda but it support very few drivers. GDAL building recipe for Anaconda looks indeed very poor: <https://github.com/ContinuumIO/anaconda-recipes/blob/py27/libgdal/build.sh>
GDAL from other chanels (e.g.) osgeo depens on many osgeo packages and makes it troublesome to install other components. E.g. osgeo/gdal depend on osgeo/geos 4.3.2 and conda/matplotlib depends on conda/geos 3.3.3. Installing both osgeo/gdal and conda/matplotlib creates unresolvable conflict.

We should aim at using as many default conda packkages as possible.

Building packages for conda seem not a very complex task:
http://docs.binstar.org/conda.html

But it has to be automated as much as possible and probably via continuous integration.

**Comment by aleksandervines** [comment]
A GDAL build for nansat is available and under testing on anaconda. Currently located at the channel https://conda.anaconda.org/alevin

The build of nansat is currently not working because of some issues with the linking of pixelfunctions. This needs to be resolved for nansat to be available through Conda. For now it is enough that it is easy to install all dependencies.

When we release the first fully tested version, we should change to nersc channel. https://conda.anaconda.org/Nersc

**Comment by aleksandervines** [comment]
I changed the Travis configuration to use this new gdal build from Conda.

The develop build now passes!

**Comment by akorosov** [comment]
Aleksander, can you please add cache to the travis.yaml file as described here:
http://docs.travis-ci.com/user/caching/

We can cache miniconda dir

**Comment by aleksandervines** [comment]
Changed travis to use the new ifrastructure (docker).
This enabled caching (as it was only available on private repositories for the old ifrastructure)
Set to cache:
    - $HOME/miniconda
Also tried to cache pip, but it seemed that it would slow the whole build down because the cache would need to be updated on each build.

I'm not really sure if this speeds up the whole build process at average. It takes some time to set up the cache, and some time to rebuild it if anything changes. I think we have to specialize it a lot more to be efficient.

The cache is quite large. (700+ MB), I'm not sure if there are any restrictions on this size, at least when we start branching out from this.

Also, for some reason, the caching process complaints about two files missing:
/home/travis/miniconda/pkgs/matplotlib-1.4.3-np110py27_2/lib/libtcl.so: No such file or directory
/home/travis/miniconda/pkgs/matplotlib-1.4.3-np110py27_2/lib/libtk.so: No such file or directory
So there seems to be something wrong somewhere

**Comment by akorosov** [comment]
Fantastic work @aleksandervines !
