### ISSUE TITLE
Change travis and coverall badges in develop to actually show develop branch

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nansat#240]
should be self-explanatory?

**Comment by mortenwh** [comment]
This seems to be solved - is that correct? Also, the badges have been kept pointing to develop after the last merges from master...

**Comment by jonbergh** [comment]
To my understanding. There is a problem in Github to get/send (catch) information about the current branch, due to security? So, when merging from Master, links to develop will be overwritten in README.rst file. See for instance:

https://github.com/travis-ci/travis-ci/issues/779
https://github.com/travis-ci/travis-ci/issues/1892
https://github.com/travis-ci/travis-ci/issues/974

These are old issues, though the problem seems still to be unsolved:

https://github.com/lemurheavy/coveralls-public/issues/281

One suggestion is to always display the Master branch:

https://github.com/elm/core/pull/515

Another is to display a fixed table of both master and develop badges in all README files:


Branch | Travis CI | Code Coverage
-- | -- | --
master |   |  
develop |   |  

https://github.com/hpi-swa-teaching/AcceptIt/blob/f767fc191441eaa8ffa3006e8698f081143b059e/README.md 

There are also issues with late update of the status, due to the Github catch issue 

https://github.com/lemurheavy/coveralls-public/issues/971
https://github.com/lemurheavy/coveralls-public/issues/1065

Though, seems to be a solution to add a query param (&service=github):

https://github.com/Squarespace/datasheets/pull/10

**Comment by jonbergh** [comment]
Trying out this in 
https://github.com/nansencenter/nansat/tree/issue240_travis_coverall_badges_show_develop

Tested first with old issues where build status and coverage fail, to see that badges show up correctly:
https://github.com/nansencenter/nansat/commit/3eff534275c8b0e99cf85feb20994904f1338191

then with the correct master and develop branches:
https://github.com/nansencenter/nansat/commit/6740cb0cc6b248abc9e76858731f9ea6f608137b

**NOTE!** The link related to the Travis CI badges is to the overview of all branches, because otherwise it always link to the last updated branch! Though, the badges should represent the correct branch, master and develop respectively (tested above)!

**Comment by jonbergh** [comment]
@mortenwh if this looks ok, I will do a pull request?

**Comment by mortenwh** [comment]
Yes, if I understand correctly, the badges are now showing master and develop only, right? Not the last commit in any branch? If that's the case, I think it could be merged, so very good if you could make a pull request 👍

**Comment by mortenwh** [comment]
btw - remember to assign yourself on the issues you're working on...
