### ISSUE TITLE
Wind model mappers

### ISSUE THREAD

**Issue by korvinos** [nansencenter/nansat#305]
Model data (ECMWF, COSMO, NORA10) are usually provided in NetCDF files with hundreds of bands (1 band for each time step). Reading of this files with existing mappers takes tremendous time. Therefore a new mapper (mappers) should be developed. 

Questions: 
1. Should a mapper be more generic (read as many different data (models) as possible) or more specific (one model - one mapper?
2. From my point of view, xarrays looks like a very useful tool for the handling this sort of data. However, if I decide to use that for the mapper, it will bring an additional dependency. Is that ok? 
3. Do we need these mappers in nansat or should I develop them separately and keep as additional mappers somewhere?

**Comment by mortenwh** [comment]
Have you tried the netcdf-cf mapper? It has functionality for reading only given timesteps etc. Unless it has what you request, this could be extended or updated...

**Comment by akorosov** [comment]
1. I think generic parts can be move to an upper class mapper (e.g. netcdf-cf) but the details about specific formats, structure, use of xarrays, etc should be in a separate mapper for your data.
2. Dependency on xarray can be optional. If it is imported only in the mapper_ECMWF then simply this mapper is disabled when xarray is not available. That's how it is done for sentinel1.
3. Would be very nice to have it in Nansat eventually!

#### Generall comment.
The current netcdf-cf mapper is inefficient for these kinds of datasets. So if you know structure of your data apriori, you don't even need to use xarrays because you can create VRT very fast without using gdal (e.g. by using only netCDF4.Dataset).
